######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 13 21:09:16 2008
######################################################################
include(quickflickr.pri)

unix:!symbian:!maemo5 {
    target.path = /opt/quickflickr/bin
    INSTALLS += target
}
